### ISSUE TITLE
GUI - File overview, Contract create/form

### ISSUE THREAD

**Issue by chopan-7** [ka11i0/BetterFilesharing#23]
**File**

1. List all shareable files
2. Access table (create/modify)

**Contracts**

1. Add condition name and description to json-contract file
2. Form: select file from shareable files
3. Form: edit contract (only sender)

**Comment by ka11i0** [comment]
File:
3. Add shareable files

**Comment by chopan-7** [comment]
7 h

**Comment by HectorNyblom** [comment]
7h
